import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";
import { metadata, HTML_LANG } from "@/lib/metadata";
import { APP_NAME } from "@/lib/constants";

const webRoot = path.resolve(__dirname, "..");
const baca = (rel: string) => readFileSync(path.join(webRoot, rel), "utf8");

const layout = baca("src/app/layout.tsx");
const globals = baca("src/app/globals.css");
const halamanMasuk = baca("src/app/masuk/page.tsx");

describe("identitas aplikasi", () => {
  it("dokumen berbahasa Indonesia", () => {
    expect(HTML_LANG).toBe("id");
    expect(layout).toContain("lang={HTML_LANG}");
    expect(layout).not.toContain('lang="en"');
  });

  it("metadata judul memakai template dan bukan boilerplate", () => {
    const title = metadata.title as { default: string; template: string };
    expect(title.template).toBe(`%s · ${APP_NAME}`);
    expect(title.default).toContain(APP_NAME);
    expect(title.default).not.toMatch(/create next app/i);
  });

  it("deskripsi berbahasa Indonesia sesuai layanan PADMA", () => {
    const description = metadata.description ?? "";
    expect(description).not.toMatch(/generated by create next app/i);
    expect(description.length).toBeGreaterThan(40);
    expect(description).toMatch(/promil/i);
    expect(description).toMatch(/perempuan/i);
  });

  it("halaman anak mengandalkan template judul", () => {
    expect(halamanMasuk).toMatch(/title:\s*"Masuk"/);
    expect(halamanMasuk).not.toMatch(/title:\s*"Masuk[^"]*PADMA"/);
  });

  it("tiga font brand didaftarkan lewat next/font/google", () => {
    expect(layout).toMatch(/from ["']next\/font\/google["']/);
    for (const loader of ["Marcellus", "Plus_Jakarta_Sans", "IBM_Plex_Mono"]) {
      expect(layout).toContain(loader);
    }
    for (const variabel of [
      "--font-marcellus",
      "--font-jakarta",
      "--font-plex-mono",
    ]) {
      expect(layout).toContain(variabel);
    }
  });

  it("token Tailwind dipetakan ke font brand", () => {
    expect(globals).toMatch(/--font-serif:\s*var\(--font-marcellus\)/);
    expect(globals).toMatch(/--font-sans:\s*var\(--font-jakarta\)/);
    expect(globals).toMatch(/--font-mono:\s*var\(--font-plex-mono\)/);
  });

  it("tidak menyisakan font Geist", () => {
    expect(layout).not.toMatch(/geist/i);
    expect(globals).not.toMatch(/geist/i);
  });
});
